# Generated by Django 5.0.14 on 2026-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'ASBL")),
                ('address', models.TextField(verbose_name='Adresse du siège social')),
                ('enterprise_number', models.CharField(blank=True, default='', max_length=20, verbose_name="Numéro d'entreprise (BCE)")),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
    ]
