# Generated by Django 5.0.14 on 2026-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
