# Generated by Django 5.0.14 on 2026-04-14 01:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('category_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.organization')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['category_type', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé')], default='open', max_length=10, verbose_name='Statut')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='core.organization')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/%Y/%m/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Écriture',
                'verbose_name_plural': 'Écritures',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du relevé')),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Caisse')),
                ('bank', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Banque')),
                ('receivables', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Créances')),
                ('debts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Dettes')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_snapshots', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'État du patrimoine',
                'verbose_name_plural': 'États du patrimoine',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant prévu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.category')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('fiscal_year', 'category')},
            },
        ),
    ]
