# Generated by Django 5.0.14 on 2026-04-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name', 'category_type')},
        ),
    ]
